[Interface]
Address = 10.252.2.2
PrivateKey = 6HsO8nbtCf9wR8jG83CCOo+U7e+jzUfJWLqIMuvu1Ek=
DNS = 10.101.10.10

[Peer]
PublicKey = /OoXstCiQUqP57JlVBFy+KekcH7rdZiIyPgo/4tZWxE=
PresharedKey = VhMwdTIJxTj4jn8WPpRhV8RAS06qwKEqKn3IpwEAlq4=
Endpoint = 192.168.1.157:51821
AllowedIPs = 10.101.10.0/24,10.101.20.0/24,10.101.30.0/24
