[Interface]
Address = 10.252.7.2
PrivateKey = sHy332RbEm7r9FCmEUtgZk9rVALQYNtTqEFI5Q0R1EQ=
DNS = 10.106.10.10

[Peer]
PublicKey = shMCEeKDRTrjjxi85zY9sCEkYnTeRpq4CIaBc6tTpTI=
PresharedKey = qH/f1OPOZtFcqw9J5dsHAQYz+jesmehnuF0LjhvhG5E=
Endpoint = 127.0.0.1:51826
AllowedIPs = 10.106.10.0/24,10.106.20.0/24
