[Interface]
Address = 10.252.4.2
PrivateKey = IK7YntFCD5r/SNjJmH3RZlWcNyggh2rfDwJcXc0jiEY=
DNS = 10.103.10.10

[Peer]
PublicKey = q8x51b4RhfviN+mrfqh6zWjmuR4NHjncoPzq8coVGmM=
PresharedKey = T/Rvsb/xCTyrNscfIV3O81Mp6f8HaLPaqcmX7Y8ZhVE=
Endpoint = 192.168.1.157:51823
AllowedIPs = 10.103.10.0/24,10.103.20.0/24
