[Interface]
Address = 10.252.1.2
PrivateKey = gDeirlDPqf0RpvCcdmBh2FwUruTF063QxNgNIfP9k3M=
DNS = 10.107.10.10

[Peer]
PublicKey = eFV5P7urLkVjmO0w9TPSqVRfAvfmW1+s1+PlGIWnASk=
PresharedKey = Tv/jiq7HST5OY2nemXKAox/bNlMqCrBNOhlBP3T/7f8=
Endpoint = 192.168.1.157:51820
AllowedIPs = 10.107.10.0/24,10.107.20.0/24
