[Interface]
Address = 10.252.1.2
PrivateKey = eKlo5C3dO52DKPOsfCb8GY/odU/TDo8rZwPyJaCtZU0=
DNS = 10.108.10.10

[Peer]
PublicKey = cx2YhKSsquRebZ8/PCPvZeJXPDqc6QPLNqjFSS8cqEw=
PresharedKey = /nssyPwTFHw3i9WCH04lZ7RTXwrLZsrYDMH5MoAT2+Y=
Endpoint = 192.168.1.157:51820
AllowedIPs = 10.108.10.0/24,10.108.20.0/24
