[Interface]
Address = 10.252.6.2
PrivateKey = QCJAu2J43CczO7IqcsFs+u8AJcaqUSUEu9ZAGLSJhnc=
DNS = 10.105.10.10

[Peer]
PublicKey = N5TJcFwVRP55UOOjnobxHZeOi34epsDLJC2uAzsZCRU=
PresharedKey = 9SY4xooYpR+SCiSmHSQgHfp3U6CkBA/MyhF0hfF6LkI=
Endpoint = 192.168.1.157:51825
AllowedIPs = 10.105.10.0/24,10.105.20.0/24
