[Interface]
Address = 10.252.1.2
PrivateKey = eGuhuChtxo3jAyeJbruxTp2WE2DSD54seZ6sYxTqNEo=
DNS = 10.104.10.10

[Peer]
PublicKey = YK5rMyZvxnpRxUHmpf4c6nQRGxN072mj1qt3kR5ARWw=
PresharedKey = NLl0T9DSfrHHrsyBuIdXzRVQ3c7OGpoFOLg5ulscGOE=
Endpoint = 192.168.1.157:51820
AllowedIPs = 10.104.10.0/24,10.104.20.0/24
