[Interface]
Address = 10.252.3.2
PrivateKey = EG/X/WdxLgO62ln/CzsJUvvsACplcgoy+S6MCLm6130=
DNS = 10.102.10.10

[Peer]
PublicKey = MMy0M64YZhVdJEzguTJkZMUl1ZJIniNjUn+5FicUYBk=
PresharedKey = 7eGUK+hGKr6QYVVy5ltM4qsfD8FDAM3m4hz5ZegJM0g=
Endpoint = 127.0.0.1:51822
AllowedIPs = 10.102.10.0/24,10.102.20.0/24
