[Interface]
Address = 10.252.10.2
PrivateKey = EBkNaHjQKaHDoYe1bLgKp8frMLOPo8pZDVfcVjmeEVY=
DNS = 10.109.10.10

[Peer]
PublicKey = liOmLBWXRfhkngo61/+ukk8TdJ2xouQEy28YNdJn/QI=
PresharedKey = zN1lVWMan086cWoBEs7Bfbsr8Hl+ui38FYgQmUmY57E=
Endpoint = 192.168.1.157:51829
AllowedIPs = 10.109.10.0/24,10.109.20.0/24
